spring:
  application:
    name: backend

external-api:
  kakao:
    base-url: https://dapi.kakao.com
    rest-api-key: ${KAKAO_REST_API_KEY}

  kma:
    base-url: https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
    service-key: ${KMA_SERVICE_KEY}